package chap4;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public class CountDownTimerGUI extends javax.swing.JFrame {

    int min, sec, min1, sec1, hr, hr1;
    Timer timer;
    boolean isStop = false;

    /**
     * Creates new form CountDownTimerGUI
     */
    public CountDownTimerGUI() {
        initComponents();
        for (int i = 0; i < 60; i++) {
            if (i < 10) {
                cbxMin.addItem("0" + i);
            } else {
                cbxMin.addItem("" + i);
            }
        }
        for (int i = 0; i < 60; i++) {
            if (i < 10) {
                cbxSec.addItem("0" + i);
            } else {
                cbxSec.addItem("" + i);
            }
        }
        for (int i = 0; i < 24; i++) {
            if (i < 10) {
                cbxHr.addItem("0" + i);
            } else {
                cbxHr.addItem("" + i);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblMin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblSec = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        cbxSec = new javax.swing.JComboBox<>();
        cbxMin = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblHr = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        uu = new javax.swing.JLabel();
        cbxHr = new javax.swing.JComboBox<>();
        btnAdd10 = new javax.swing.JButton();
        btnAdd15 = new javax.swing.JButton();
        btnAdd30 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Count Down Timer by tusnim");

        jLabel1.setDisplayedMnemonic('C');
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Count Down Timer by tusnim");

        lblMin.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblMin.setForeground(new java.awt.Color(102, 255, 102));
        lblMin.setText("00");
        lblMin.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblMinAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setText(":");

        lblSec.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblSec.setForeground(new java.awt.Color(153, 255, 153));
        lblSec.setText("00");

        btnStart.setBackground(new java.awt.Color(51, 255, 0));
        btnStart.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnStop.setBackground(new java.awt.Color(255, 0, 0));
        btnStop.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnStop.setText("stop");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        cbxSec.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbxSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSecActionPerformed(evt);
            }
        });

        cbxMin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbxMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMinActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Minute");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Second");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chap4/pngtree-alarm-clock-icon-png-image_1749230.jpg"))); // NOI18N

        lblHr.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblHr.setForeground(new java.awt.Color(0, 255, 0));
        lblHr.setText("00");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel4.setText(":");

        uu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        uu.setText("Hour");

        cbxHr.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbxHr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxHrActionPerformed(evt);
            }
        });

        btnAdd10.setText("10 minutes");
        btnAdd10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd10ActionPerformed(evt);
            }
        });

        btnAdd15.setText("15 minutes");
        btnAdd15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd15ActionPerformed(evt);
            }
        });

        btnAdd30.setText("30 minutes");
        btnAdd30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd30ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cbxSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uu)
                            .addComponent(lblHr)
                            .addComponent(cbxHr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3))
                            .addComponent(jLabel5)
                            .addComponent(cbxMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSec)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd30)
                    .addComponent(btnAdd15)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnAdd10))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMin)
                                    .addComponent(lblSec)
                                    .addComponent(jLabel3)
                                    .addComponent(lblHr)
                                    .addComponent(jLabel4))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(uu)
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(btnStart)
                                .addGap(27, 27, 27)
                                .addComponent(btnStop)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbxHr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbxMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdd10)
                                .addGap(18, 18, 18)
                                .addComponent(btnAdd15)
                                .addGap(18, 18, 18)
                                .addComponent(btnAdd30)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        btnStart.setEnabled(false);
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                if (isStop) {
                    min = min1;
                    sec = sec1;
                    hr = hr1;
                    isStop = false;

                }
                if (sec < 1) {
                    sec = 60;
                    min--;
                }
                if (min < 0) {
                    min = 59;
                    hr--;

                }

                if (hr < 0) {
                    JOptionPane.showMessageDialog(rootPane, "หมดเวลา");
                    min = 0;
                    sec = 0;
                    hr = 0;
                    timer.stop();
                    btnStart.setEnabled(true);
                } else {
                    sec--;
                }
                if (min < 10) {
                    lblMin.setText("0" + min);
                } else {
                    lblMin.setText("" + min);
                }
                if (sec < 10) {
                    lblSec.setText("0" + sec);
                } else {
                    lblSec.setText("" + sec);
                }
                if (hr < 10) {
                    lblHr.setText("0" + hr);
                } else {
                    lblHr.setText("" + hr);
                }

            }

        });
        timer.start();


    }//GEN-LAST:event_btnStartActionPerformed

    private void cbxSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSecActionPerformed
        lblSec.setText("" + cbxSec.getSelectedItem());
        sec = Integer.parseInt(lblSec.getText());
    }//GEN-LAST:event_cbxSecActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        btnStart.setEnabled(true);
        min1 = min;
        sec1 = sec;
        isStop = true;
        timer.stop();
    }//GEN-LAST:event_btnStopActionPerformed

    private void cbxMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMinActionPerformed
        lblMin.setText("" + cbxMin.getSelectedItem());
        min = Integer.parseInt(lblMin.getText());
    }//GEN-LAST:event_cbxMinActionPerformed

    private void btnAdd10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd10ActionPerformed
        min = 10;
        lblMin.setText("" + min);
    }//GEN-LAST:event_btnAdd10ActionPerformed

    private void lblMinAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblMinAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMinAncestorAdded

    private void cbxHrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxHrActionPerformed
        lblHr.setText("" + cbxHr.getSelectedItem());
        hr = Integer.parseInt(lblHr.getText());
    }//GEN-LAST:event_cbxHrActionPerformed

    private void btnAdd15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd15ActionPerformed
        min = 15;
        lblMin.setText("" + min);
    }//GEN-LAST:event_btnAdd15ActionPerformed

    private void btnAdd30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd30ActionPerformed
        min = 30;
        lblMin.setText("" + min);
    }//GEN-LAST:event_btnAdd30ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CountDownTimerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CountDownTimerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CountDownTimerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CountDownTimerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CountDownTimerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd10;
    private javax.swing.JButton btnAdd15;
    private javax.swing.JButton btnAdd30;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JComboBox<String> cbxHr;
    private javax.swing.JComboBox<String> cbxMin;
    private javax.swing.JComboBox<String> cbxSec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblHr;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblSec;
    private javax.swing.JLabel uu;
    // End of variables declaration//GEN-END:variables
}
