/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chap4.MiniProject;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class FortuneTellingGUI extends javax.swing.JFrame {

    /**
     * Creates new form FortuneTelling
     */
    public FortuneTellingGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        rdbMonDay = new javax.swing.JRadioButton();
        rdbWednesDay = new javax.swing.JRadioButton();
        rdbTuesDay = new javax.swing.JRadioButton();
        rdbThursDay = new javax.swing.JRadioButton();
        rdbFriday = new javax.swing.JRadioButton();
        rdbSaturday = new javax.swing.JRadioButton();
        rdbSunday = new javax.swing.JRadioButton();
        bntSubmit = new javax.swing.JButton();
        lblLove = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tarPer = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tarPerlove = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("by tusnim");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setText("ทำนายดวงความรักตามวันเกิด");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("วันเกิด");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("นิสัย");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("นิสัยเวลามีความรัก");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("ระดับความครั่งรัก");

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbMonDay);
        rdbMonDay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdbMonDay.setText("วันจันทร์");
        rdbMonDay.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rdbMonDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbMonDayActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbWednesDay);
        rdbWednesDay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdbWednesDay.setText("วันพุธ");
        rdbWednesDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbWednesDayActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbTuesDay);
        rdbTuesDay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdbTuesDay.setText("วันอังคาร");
        rdbTuesDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbTuesDayActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbThursDay);
        rdbThursDay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdbThursDay.setText("วันพฤหัสบดี");
        rdbThursDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbThursDayActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbFriday);
        rdbFriday.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdbFriday.setText("วันศุกร์");
        rdbFriday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbFridayActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbSaturday);
        rdbSaturday.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdbSaturday.setText("วันเสาร์");
        rdbSaturday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbSaturdayActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbSunday);
        rdbSunday.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdbSunday.setText("วันอาทิตย์");
        rdbSunday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbSundayActionPerformed(evt);
            }
        });

        bntSubmit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bntSubmit.setText("ทำนาย");
        bntSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSubmitActionPerformed(evt);
            }
        });

        lblLove.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblLove.setForeground(new java.awt.Color(255, 0, 0));
        lblLove.setText("0%");

        tarPer.setColumns(20);
        tarPer.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        tarPer.setRows(5);
        jScrollPane1.setViewportView(tarPer);

        tarPerlove.setColumns(20);
        tarPerlove.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        tarPerlove.setRows(5);
        jScrollPane2.setViewportView(tarPerlove);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdbMonDay)
                                    .addComponent(rdbThursDay)
                                    .addComponent(rdbSunday))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bntSubmit)
                                    .addComponent(rdbFriday)
                                    .addComponent(rdbTuesDay))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdbWednesDay)
                                    .addComponent(rdbSaturday))))
                        .addContainerGap(115, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLove))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(rdbMonDay)
                            .addComponent(rdbWednesDay))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdbThursDay)
                            .addComponent(rdbSaturday)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdbTuesDay)
                        .addGap(18, 18, 18)
                        .addComponent(rdbFriday)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbSunday)
                    .addComponent(bntSubmit))
                .addGap(4, 4, 4)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblLove))
                .addGap(18, 18, 18)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbMonDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbMonDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbMonDayActionPerformed

    private void rdbWednesDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbWednesDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbWednesDayActionPerformed

    private void rdbTuesDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbTuesDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbTuesDayActionPerformed

    private void rdbThursDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbThursDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbThursDayActionPerformed

    private void rdbFridayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbFridayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbFridayActionPerformed

    private void rdbSaturdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbSaturdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbSaturdayActionPerformed

    private void rdbSundayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbSundayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbSundayActionPerformed

    private void bntSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSubmitActionPerformed
        String Per = null, Perlove = null;
        int num;

        if (rdbMonDay.isSelected()) {
            Per = "ปกติคนที่เกิดวันนี้เป็นคนที่ค่อนข้างแพรวพราว เป็นคนที่ค่อนข้างจะรักอิสระ\n"
                    + "ดูเป็นคนเจ้าชู้ไม่รู้ตัว เพราะเป็นคนมีเสน่ห์ วางตัวดี";
            Perlove = "ถ้ามีความรักขึ้นมาล่ะก็ เหมือนเป็นคนละคน! จากเสีอตัวใหญ่ \n"
                    + "พอมีแฟนแล้วจะกลายเป็นแมวน้อย ขี้อ้อน เอาใจ อยากได้อะไรจัดให้ทุกอย่าง งอแงกับแฟนเพราะอยากเรียกร้อง\n"
                    + "ความสนใจ ถ้าคบกันแล้วก็อยากให้ดูแล เอาอกเอาใจซึ่งกันและกัน มือถือนี่ถ้าไม่ล็อกรหัสก็เรียบร้อย! เพราะ\n"
                    + "คนเกิดวันนี้จะแอบหึง แอบส่องทุกอย่าง แฟนไปไหน ทําอะไร อยู่กับใคร รู้หมด! แต่คนที่เกิดวันจันทร์ถึงจะมี\n"
                    + "แฟนยังไงก็ยังไม่ทิ้งเพื่อน ถ้าอีกฝ่ายเข้าใจ ไม่คิดมากก็คบกันได้ยาว ๆ จ้า";
            lblLove.setText("90%");

        } else if (rdbTuesDay.isSelected()) {
            Per = "คนเกิดวันนี้เป็นพ่อแม่บุญทุ่ม เวลารักใครจะจริงจังมากระดับสิบ! เป็นคนใจร้อน ตอบช้า 5 นาทีจะรู้สึกใจหายแล้ว \nว่าเราพูดอะไรผิดไปไหมนะ? หรือว่าเขาไม่อยากคุยกับเราหรือเปล่า? หรือว่าเกิดเหตุร้ายอะไรขึ้น\n เอ๊ะ! หรือว่าแอบคุยกับคนอื่น";
            Perlove = "ถ้าอยู่ในช่วงอินเลิฟแล้วจะอารมณ์ดีทั้งวัน ยิ้มคนเดียว เป็นคนติดแฟน อยากอยู่ด้วยตลอดเวลา เธออยู่ที่ไหน จะไปอยู่ตรงหน้า จะไปหาแน่ ๆ! \nและค่อนข้างคาดหวังในตัวคนรักมาก ๆ ถ้าให้ 100 ต้องได้กลับมา 100 ชอบอะไรที่แฟร์ ๆ\n ถ้าไม่แฟร์ก็หาใหม่ ชอบความตื่นเต้นท้าทาย ถ้าอีกฝ่ายเล่นตัวนิดหน่อย เข้าหาบ้าง เอาใจก่อนบ้าง แกล้งไม่ตอบบ้าง ยิ่งตื่นเต้น ยิ่งถ้าอีกฝ่ายใส่ใจ \nและเข้าใจในตัวของคนที่เกิดวันอังคาร รับรองว่ารักจนมูฟออนไปไหนไม่ได้!";
            lblLove.setText("100%");
        } else if (rdbWednesDay.isSelected()) {
            Per = "คารมดีเป็นที่ 1 ตบมุขโบ๊ะบ๊ะได้ ทันคน เทคนิคอ่อยชั้นครู แพรวพราวพอ ๆ กับคนเกิดวันจันทร์ เป็นคนที่ค่อยๆ ดู ค่อยๆ เก็บข้อมูลฝ่ายตรงข้าม ไม่วู่วาม ชอบนะ แต่ไม่แสดงออกตรง ๆ \nรอจนกว่าจะแน่ใจจริง ๆ แล้วถึงจะตกลงเป็นแฟน";
            Perlove = " เป็นคนที่รักใครแล้วรักจริง โรแมนติก เรื่องเล็ก ๆ น้อยก็จำได้ เอาใจใส่แฟนหรือคนรักมาก แต่ข้อเสียของคนที่เกิดวันนี้ เป็นเพราะอีโก้ที่สูงเสียดฟ้า อาจจะทำให้เรื่องราวที่มันไม่ได้มีอะไรเลย พังได้ง่ายๆ \nเพราะความมีอีโก้ของตัวเอง เวลาโกรธมาก็จะใช้คำพูดที่ไม่ค่อยดี เป็นคนคาดหวังกับความรักสูง คิดมาก ขี้หึง ขี้ระแวง \nแล้วพอไม่ได้ตามที่หวัง ก็อาจจะพาลเบื่อได้ง่าย ๆ แนะนำให้ใจเย็น ๆ และลดความคาดหวังกับอีโก้ลงนิดหน่อย จะทำให้ความรักไปได้ดี";
            lblLove.setText("50%");
        } else if (rdbThursDay.isSelected()) {
            Per = "ภายนอกอาจจะดูเป็นคนอ่อยเก่ง แพรวพราว แต่จริงๆ แล้วเป็นคนค่อนข้างอ่อนไหว เป็นคนออกจะบ๊องๆ ขาดๆ เกินๆ \nด้วยซ้ำ คนเกิดวันนี้ถึงจะดูอ่อยเก่งก็จริง ดูเป็นสาวฮอต หนุ่มฮอต แต่รักใครแล้วรักจริงจังมาก \nไม่ชอบการนอกใจ และการถูกหักหลัง";
            Perlove = "เวลาคนเกิดวันพฤหัสบดีมีความรักแล้วเหมือนเมากัญชา อารมณ์ดีทั้งวัน และวันครบรอบ วันเกิด จำได้หมด \nตกหลุมรักคนง่าย ยิ่งถ้าเจอคนที่คุยแบบ Deep Conversation ได้ ยิ่งชอบ \nชอบคนที่เป็นผู้ใหญ่ ยิ่งมีทัศนคติดีๆ หรือพลังบวก คนที่เกิดวันพฤหัสบดีจะมโนไปถึงขั้นแต่งงานเลย ทั้งๆ ที่แค่เริ่มคุย \nแต่ก็ชอบความรักที่ค่อยเป็นค่อยไป ไม่รีบนะ";
            lblLove.setText("60%");
        } else if (rdbFriday.isSelected()) {
            Per = "คนเกิดวันนี้ออกแนวพ่อบ้านใจกล้า ไม่เถียงหรอกนะ แต่อย่าให้โกรธ! เป็นคนช่างมโน \nชอบเพ้อเงียบๆ เป็นตุเป็นตะอยู่คนเดียว และคนเกิดวันนี้เป็นคนอ่อนโยน \nเอาใจใส่แฟนมาก ต้องการให้แฟนเอาใจใส่ตัวเองเหมือนกัน ถ้าเจอคนที่ทำให้คนเกิดวันศุกร์รู้สึกรักทั้งแฟน รักทั้งตัวเอง \nหรือชอบตัวเองตอนอยู่กับแฟน จะเป็นอะไรที่เพอร์เฟ็กต์มาก";
            Perlove = "ใครชอบคนสายเปย์ มาทางนี้! คนเกิดวันศุกร์บอกเลยว่าเปย์เก่งงงง ชอบหาอะไรทำ ชวนแฟนทำนู่น ทำนี่ อยู่ด้วยแล้วไม่มีทางเบื่อแน่นอน \nและมักจะเจอคนที่แตกต่างกันที่ อายุ เชื้อชาติ ศาสนา ฐานะ ฯลฯ แต่ไม่ค่อยสนใจเท่าไร \nถ้าพร้อมจะเดินไปด้วยกันก็โอเค คบกันได้ยาว ๆ";
            lblLove.setText("85%");
        } else if (rdbSaturday.isSelected()) {
            Per = "คนที่เกิดวันเสาร์ชอบทำตัวเป็นผู้นำ อีโก้สูง บ้าพลัง ไม่ชอบคนต่อล้อต่อเถียง ฉะนั้นคนที่นิ่ง ๆ สุขุมหน่อยๆ ก็จะเข้าทางคนที่เกิดวันนี้ เป็นคนเด็ดขาด ชัดเจน \nชอบก็คือชอบ ไม่ยึกๆ ยักๆ ชอบคนเอาใจ ใส่ใจ ชอบอะไรที่เรียบง่าย มั่นคง \nถ้ามีแฟนแล้วก็จะทุ่มสุด ๆ";
            Perlove = "อยากได้อะไรบอกจะจัดให้ตามที่ขอทุกอย่าง ยกเว้นให้ลุงลาออก (เอ๊ย! ไม่ใช่!) ดูแลแฟนหรือคนรักดีเว่อร์! \nเหมือนเราเป็นเจ้าหญิงหรือเจ้าชาย แต่ไม่ชอบอะไรที่จุกจิก \nชนิดว่าตามหึงตามจิกเกินเบอร์จะเบื่อมาก แต่ถึงจะไม่ชอบอะไรแบบนั้น \nคนที่เกิดวันเสาร์เวลาหึงจะน่ากลัวระดับสิบ!";
            lblLove.setText("70%");
        } else {
            Per = "คนที่เกิดวันอาทิตย์ เขาว่าเป็นคนอารมณ์ขึ้นๆ ลงๆ อาจจะตามอารมณ์ยากสักหน่อย \nเป็นคนใจกว้าง ให้อิสระกับคนรัก แต่ถ้าเข้าโหมดจริงจังแล้วไม่ชอบอะไรเล่น ๆ \nอยู่ไหน ทำอะไรกับใคร ต้องบอก ต้องรายงาน \nและถ้าชอบใครก็จะทำทุกวิถีทางเพื่อให้ได้คบ";
            Perlove = "พอมีแฟนแล้วโลกสดใส อะไรก็เป็นสีชมพูไปหมด ถ้ามีแฟนจะขี้บ่นมาก ๆ แต่ก็เป็นเพราะรักแหละถึงบ่น \nเป็นคนรักเดียวใจเดียว คบใครก็คบทีละคน ไม่ได้หว่านไปทั่วถ้าเทียบกับคนเกิดวันอื่น ๆ \nถ้าเจอแฟนหรือคนรักที่เข้ากับครอบครัวหรือเพื่อนได้ก็ผ่านฉลุย เพราะชอบความรักแบบลึกซึ้ง \nพร้อมที่จะเป็นครอบครัวเดียวกันในอนาคต ชอบคนพูดเพราะ ใส่ใจ ยิ้มหวาน \nถ้าสอบผ่านก็จะเสมอต้นเสมอปลายกับคนรักมาก ๆ";
            lblLove.setText("75%");
        }

        tarPer.setText(" " + Per);
        tarPerlove.setText(" " + Perlove);
    }//GEN-LAST:event_bntSubmitActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(rootPane, "Exit");
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FortuneTellingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FortuneTellingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FortuneTellingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FortuneTellingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FortuneTellingGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntSubmit;
    private javax.swing.JButton btnExit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblLove;
    private javax.swing.JRadioButton rdbFriday;
    private javax.swing.JRadioButton rdbMonDay;
    private javax.swing.JRadioButton rdbSaturday;
    private javax.swing.JRadioButton rdbSunday;
    private javax.swing.JRadioButton rdbThursDay;
    private javax.swing.JRadioButton rdbTuesDay;
    private javax.swing.JRadioButton rdbWednesDay;
    private javax.swing.JTextArea tarPer;
    private javax.swing.JTextArea tarPerlove;
    // End of variables declaration//GEN-END:variables
}
