package chap4.MiniProject;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class LetterPostShop extends javax.swing.JFrame {

    private Object txtPrice;

    /**
     * Creates new form LetterPostShop
     */
    public LetterPostShop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txtWeight = new javax.swing.JTextField();
        btnComrute = new javax.swing.JButton();
        rdbNoraml = new javax.swing.JRadioButton();
        rdbRegister = new javax.swing.JRadioButton();
        rdbEMS = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tarResult = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("by tusnim");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("ส่งจดหมาย");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("ประเภทจดหมาย");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("น้ำหนักจดหมาย(g)");

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        txtWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeightActionPerformed(evt);
            }
        });
        txtWeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtWeightKeyTyped(evt);
            }
        });

        btnComrute.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnComrute.setText("คำนวณราคา");
        btnComrute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComruteActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbNoraml);
        rdbNoraml.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdbNoraml.setText("ธรรมดา");
        rdbNoraml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbNoramlActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbRegister);
        rdbRegister.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdbRegister.setText("ลงทะเบียน");

        buttonGroup1.add(rdbEMS);
        rdbEMS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdbEMS.setText("EMS");
        rdbEMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbEMSActionPerformed(evt);
            }
        });

        tarResult.setColumns(20);
        tarResult.setRows(5);
        jScrollPane1.setViewportView(tarResult);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(183, 183, 183)
                                        .addComponent(rdbNoraml)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdbRegister)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdbEMS))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(25, 25, 25)
                                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnComrute)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btnClear)
                        .addGap(84, 84, 84)
                        .addComponent(btnExit)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rdbNoraml)
                    .addComponent(rdbRegister)
                    .addComponent(rdbEMS))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComrute))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(btnClear))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(rootPane, "Exit");
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void rdbEMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbEMSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbEMSActionPerformed

    private void rdbNoramlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbNoramlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbNoramlActionPerformed

    private void btnComruteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComruteActionPerformed
        String Price = txtWeight.getText();
        if (Price.length() > 0) {
            if (rdbNoraml.isSelected()) {
                String weightS = txtWeight.getText();
                int weight = Integer.valueOf(weightS);
                int weightre = 0;
                if (weight <= 20) {
                    weightre = 3;
                } else if (weight <= 100) {
                    weightre = 5;
                } else if (weight <= 250) {
                    weightre = 9;
                } else if (weight <= 500) {
                    weightre = 15;
                } else if (weight <= 1000) {
                    weightre = 25;
                } else if (weight <= 2500) {
                    weightre = 25;
                }
                weightS = String.valueOf(weightre);
                tarResult.setText("Normal Letter Service Price : " + weightS + " Bath");
            } else if (rdbRegister.isSelected()) {
                String weightS = txtWeight.getText();
                int weight = Integer.valueOf(weightS);
                int weightre = 0;
                if (weight <= 20) {
                    weightre = 3;
                } else if (weight <= 100) {
                    weightre = 5;
                } else if (weight <= 250) {
                    weightre = 9;
                } else if (weight <= 500) {
                    weightre = 15;
                } else if (weight <= 1000) {
                    weightre = 25;
                } else if (weight <= 2500) {
                    weightre = 25;
                }
                weightre += 13;
                weightS = String.valueOf(weightre);
                tarResult.setText("Register Letter Service Price : " + weightS + " Bath");
            } else if (rdbEMS.isSelected()) {
                String weightS = txtWeight.getText();
                int weight = Integer.valueOf(weightS);
                int weightre = 0;
                if (weight <= 20) {
                    weightre = 27;
                } else if (weight <= 100) {
                    weightre = 32;
                } else if (weight <= 250) {
                    weightre = 37;
                } else if (weight <= 500) {
                    weightre = 47;
                } else if (weight <= 1000) {
                    weightre = 62;
                } else if (weight <= 2500) {
                    weightre = 77;
                }
                weightS = String.valueOf(weightre);
                tarResult.setText("EMS Letter Service Price : " + weightS + " Bath");
            }
        }

    }//GEN-LAST:event_btnComruteActionPerformed

    private void txtWeightKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWeightKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightKeyTyped

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        tarResult.setText("");
        txtWeight.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LetterPostShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LetterPostShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LetterPostShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LetterPostShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LetterPostShop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnComrute;
    private javax.swing.JButton btnExit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdbEMS;
    private javax.swing.JRadioButton rdbNoraml;
    private javax.swing.JRadioButton rdbRegister;
    private javax.swing.JTextArea tarResult;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables

    private static class rdbNomal {

        private static boolean isSelected() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public rdbNomal() {
        }
    }

    private static class rdbRegis {

        public rdbRegis() {
        }
    }
}
